FROM php:8.2-apache

# Habilita extensões
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Habilita mod_rewrite do Apache (se precisar futuramente)
RUN a2enmod rewrite

# Define o timezone (opcional)
ENV TZ=America/Sao_Paulo
